### ISSUE TITLE
Time remaining innacurate

### ISSUE THREAD

**Issue by jacobtender** [Atelier-Shiori/SwinsianDiscord#1] opened 2019-05-05 00:06 UTC
When viewing the SwinsainDiscord information via the user menu, the "time left" does not show the time remaining for the track. Instead, time remaining restarts at 23:59:59 for each track.

**Comment by jacobtender** [comment] 2019-05-05 00:08
<img width="252" alt="Screen Shot 2019-05-04 at 8 06 56 PM" src="https://user-images.githubusercontent.com/22992052/57186179-57510780-6ea8-11e9-8b8a-d0a8c641a165.png">

**Comment by moyitpro** [comment] 2019-05-06 17:37
fixed with https://github.com/Atelier-Shiori/SwinsianDiscord/commit/9cb421385f5ee7790a059e126239ca9ac4a488ed

**Closed as completed by moyitpro** 2019-05-06 17:37 UTC

**Comment by jacobtender** [comment] 2019-05-07 00:02
@moyitpro Thank you for taking a look at this so quickly! When playback is initiated, the time remaining is reflected correctly, but I've noticed an additional bug when pause/play is used.

When a track plays, the correct time remaining is displayed in the view pictured above. When paused, the time jumps to 23:59:59 and begins counting down. On resume, the time is reset to the full length of the track and begins counting down.

**Comment by moyitpro** [comment] 2019-05-07 00:20
@jacobtender When paused, the time resets to 24 hrs. This is by design since it's not possible to clear out the end time or pause it. 

I reproduced the bug, but it seems that the capitalization to retrieve the current position was incorrect and it's fixed. I will be reissuing the update.
